title: Qasim Iqbal
baseURL: https://qas.im/
params:
  description: Qasim Iqbal's personal website.
  keywords: [Qasim Iqbal, Qasim, Iqbal, drqas, engineer, software, product, writing]
disableKinds: [sitemap, RSS, taxonomy, taxonomyTerm]
permalinks:
  posts: "/:slug/"
disableHugoGeneratorInject: true
markup:
  goldmark:
    renderer:
      unsafe: true
